# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  setup:
    name: Setup Python Environment
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest "huggingface_hub[cli,xf_xet]"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Cache pip dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Login to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_READONLY }}
        run: |
          huggingface-cli login --token "$HF_TOKEN"
      - name: Display environment
        run: |
          huggingface-cli env
          python env.py

  testgpt2:
    name: Test GPT2
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest "huggingface_hub[cli,xf_xet]"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest -k "test_gpt2_small" tests/test_gpt2.py

  testllama3:
    name: Test Llama3
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest "huggingface_hub[cli,xf_xet]"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Login to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_READONLY }}
        run: |
          huggingface-cli login --token "$HF_TOKEN"

      - name: Test with pytest
        run: |
          pytest -k "test_llama_3_dot_2_1B" tests/test_llama3.py
